apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.serverName" . }}-headless
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      targetPort: http
      port: {{ .Values.clickhouse.service.ports.http }}
      protocol: TCP
    - name: tcp
      targetPort: tcp
      port: {{ .Values.clickhouse.service.ports.tcp }}
      protocol: TCP
    - name: intrsrvhttp
      targetPort: intrsrvhttp
      port: {{ .Values.clickhouse.service.ports.intrsrvhttp }}
      protocol: TCP
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.serverName" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.clickhouse.service.type }}
  ports:
    - name: http
      targetPort: http
      port: {{ .Values.clickhouse.service.ports.http }}
      protocol: TCP
    - name: tcp
      targetPort: tcp
      port: {{ .Values.clickhouse.service.ports.tcp }}
      protocol: TCP
    - name: intrsrvhttp
      targetPort: intrsrvhttp
      port: {{ .Values.clickhouse.service.ports.intrsrvhttp }}
      protocol: TCP
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server 