apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.keeperName" . }}-headless
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: keeper
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: keeper
  ports:
    - name: keeper
      targetPort: keeper
      port: {{ .Values.keeper.service.ports.keeper }}
      protocol: TCP
    - name: http
      targetPort: http
      port: {{ .Values.keeper.service.ports.http }}
      protocol: TCP
    - name: raft
      targetPort: raft
      port: {{ .Values.keeper.service.ports.raft }}
      protocol: TCP
---
# Create a standard service for general access
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.keeperName" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: keeper
spec:
  type: {{ .Values.keeper.service.type }}
  ports:
    - name: keeper
      port: {{ .Values.keeper.service.ports.keeper }}
      targetPort: keeper
      {{- if and (eq .Values.keeper.service.type "NodePort") .Values.keeper.service.nodePorts.keeper }}
      nodePort: {{ .Values.keeper.service.nodePorts.keeper }}
      {{- end }}
    - name: http
      port: {{ .Values.keeper.service.ports.http }}
      targetPort: http
      {{- if and (eq .Values.keeper.service.type "NodePort") .Values.keeper.service.nodePorts.http }}
      nodePort: {{ .Values.keeper.service.nodePorts.http }}
      {{- end }}
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: keeper 