apiVersion: v2
name: clickhouse
description: A Helm chart for a ClickHouse cluster with ClickHouse Keeper
type: application
version: 0.2.0
appVersion: "25.3.2"
keywords:
  - clickhouse
  - database
  - sql
  - olap
  - column-store
home: https://clickhouse.com/
icon: https://clickhouse.com/images/ch-logo.svg
maintainers:
  - name: flamarion
    url: https://github.com/flamarion
sources:
  - https://github.com/ClickHouse/ClickHouse

# Trigger release
